version: '3.8'

services:
  php:
    image: php:8.2-apache
    deploy:
      replicas: 3  # Nombre de répliques du service à exécuter
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www/html

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    deploy:
      replicas: 1  # Pour les bases de données, souvent une seule réplique est suffisante
    volumes:
      - ./mysql/stagiaires.sql:/docker-entrypoint-initdb.d/stagiaires.sql:ro

  phpma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80

