version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php82
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - 3307:3306
    volumes:
      - ./mysql/stagiaires.sql:/docker-entrypoint-initdb.d/stagiaires.sql:ro

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: pass
      UPLOAD_LIMIT: 20M
    ports:
      - 8899:80
      
  
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080" # Modification du port pour éviter le conflit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: 'test:pass@tcp(db:3306)/'
    ports:
      - "9104:9104"
Ensuite, mettez à jour le fichier prometheus.yml pour qu'il scrape le nouveau port de cAdvisor :

yaml
Copier le code
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081'] # Modification du port pour correspondre à la nouvelle configuration

  - job_name: 'php_app'
    static_configs:
      - targets: ['php82:80']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
