global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'php_app'
    static_configs:
      - targets: ['php82:80']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
